Controllers/AdminController.cs
using BOOK_STORE_DEMO.Models;
using BOOK_STORE_DEMO.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BOOK_STORE_DEMO.Controllers;
[Authorize(Policy = "ADMIN")]
public class AdminController : Controller
{
    private readonly IOrderService orderService;
    private readonly IOrderItemService orderItemService;
    public AdminController(IOrderService orderService,IOrderItemService orderItemService)
    {
        this.orderService = orderService;
        this.orderItemService = orderItemService;
    }
    // GET
    public IActionResult Index()
    {
        return View();
    }


    public IActionResult Order()
    {
        IEnumerable<Order> orders=orderService.getAllOrders();
        return View(orders);
    }

    public IActionResult OrderDetail(int id)
    {
        IEnumerable<OrderItem> orderItems=orderItemService.GetOrderItemsByOrderID(id);
        return View(orderItems);
    }

    public IActionResult DeleteOrder(int id)
    {
        orderItemService.deleteByOrderID(id);
        orderService.deleteByOrderID(id);
        return RedirectToAction("Order");
    }
}

Controllers/BookController.cs
using BOOK_STORE_DEMO.Models;
using BOOK_STORE_DEMO.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace BOOK_STORE_DEMO.Controllers
{
    [Authorize(Policy = "ADMIN")]
    public class BookController : Controller
    {
        private readonly IBookService bookService;
        private readonly ICategoryService categoryService;
        private readonly IWebHostEnvironment webHostEnvironment;
        private int pageSize=4;

        public BookController(IBookService bookService, ICategoryService categoryService,IWebHostEnvironment webHostEnvironment)
        {
            this.bookService = bookService;
            this.categoryService = categoryService;
            this.webHostEnvironment = webHostEnvironment;
        }
      
        public IActionResult ListBook()
        {
            IEnumerable<Book> books=bookService.GetAllBooks();
            int pageNum=(int)Math.Ceiling((float)books.Count()/pageSize);
            ViewBag.pageNum=pageNum;
            books=books.Take(pageSize).ToList();
            return View(books);
        }

        [HttpGet]
        public IActionResult Edit(int id) 
        {
            Book book=bookService.GetBookById(id);
            ViewBag.Categories = new SelectList(categoryService.GetAllCategories(), "Id", "Name",book.CategoryId);
            return View(book); 
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Name", "Price", "Description", "Author", "PublishDate", "Publisher,CategoryId")] Book newBook,IFormFile ?imgFile)
        {
            Book oldBook= bookService.GetBookById(id);
            if (oldBook == null)
            {
                return NotFound();
            }
            if(imgFile != null && imgFile.Length > 0 && imgFile.FileName!=oldBook.ImageCover)
            {
                string folderPath = Path.Combine(webHostEnvironment.WebRootPath, "Upload\\images\\");
                string filePath = Path.Combine(folderPath, imgFile.FileName);
                string oldImgFile=Path.Combine(folderPath, oldBook.ImageCover);
                if (System.IO.File.Exists(oldImgFile)==true)
                {
                    System.IO.File.Delete(oldImgFile);
                }
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await imgFile.CopyToAsync(stream);
                }
                oldBook.ImageCover = imgFile.FileName;
            }
            else
            {
                newBook.ImageCover=oldBook.ImageCover;
            }
            oldBook.Name = newBook.Name;
            oldBook.Price= newBook.Price;
            oldBook.CategoryId = newBook.CategoryId;
            oldBook.Description= newBook.Description;
            oldBook.Author=newBook.Author;
            oldBook.PublishDate=newBook.PublishDate;
            oldBook.Publisher=newBook.Publisher;
            bookService.UpdateBook(oldBook);
            return RedirectToAction(nameof(ListBook));
        }

      
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories=new SelectList(categoryService.GetAllCategories(),"Id","Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name","Price","Description","Author","PublishDate","Publisher,CategoryId")]Book book,IFormFile imgFile) 
        {
            if(ModelState.IsValid==false)
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors);
                foreach (var error in errors)
                {
                    Console.WriteLine(error.ErrorMessage);
                }
                ViewBag.Categories = new SelectList(categoryService.GetAllCategories(), "Id", "Name");
                return View();
            }
            if (imgFile != null && imgFile.Length>0)
            {
                string folderPath = Path.Combine(webHostEnvironment.WebRootPath, "Upload\\images\\");
                string filePath=Path.Combine(folderPath,imgFile.FileName);
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await imgFile.CopyToAsync(stream);
                }
                book.ImageCover = imgFile.FileName;
                bookService.AddBook(book);
            }
            return RedirectToAction(nameof(ListBook));
        }

        public IActionResult Delete(int id)
        {
            Book book=bookService.GetBookById(id);
            string folderPath = Path.Combine(webHostEnvironment.WebRootPath, "Upload\\images\\");
            string imgFilePath = Path.Combine(folderPath, book.ImageCover);
            if (System.IO.File.Exists(imgFilePath) == true)
            {
                System.IO.File.Delete(imgFilePath);
            }
            bookService.DeleteBook(id);
            return RedirectToAction(nameof(ListBook));
        }

        public IActionResult Paging(int ?pageIndex)
        {
            int page;
            if (pageIndex == null)
            {
                page = 1;
            }
            else
            {
                page = (int)pageIndex;
            }
            IEnumerable<Book> books = bookService.GetAllBooks();
            IEnumerable<Book> result=books.Skip(pageSize*(page-1)).Take(pageSize);
            return PartialView("BookTable",result);
        }
    }
}

Views/Shared/Admin_Layout.cshtml
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title></title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">
    <link href="~/css/login.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">




@RenderBody()
<!-- Bootstrap core JavaScript-->
<script src="~/vendor/jquery/jquery.min.js"></script>
<script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="~/js/sb-admin-2.min.js"></script>

</body>

</html>

Views/Shared/MyLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
   
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/OwlCarousel2/assets/owl.carousel.css" />
        <link rel="stylesheet" href="~/OwlCarousel2/assets/owl.theme.default.css" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />
</head>
<body>
    <header>
        <div class="container">
            <div class="row">
                <div class="col-md-6 logo">
                    <a style="font-size: 28px;text-decoration: none;color: black;font-weight: normal;margin-left: 15px" asp-action="Index" asp-controller="Home">BOOKSTORE</a>
                    <div class="menu">
                        <ul style="display: flex;align-items: center">
                            <li><a asp-action="Cart" asp-controller="Home">Cart</a></li>
                               <li class="nav-item">
                                                        <input type="search" id="search-input" class="form-control" />
                                                    </li>
                                                    <li class="nav-item btn-search" >
                                                         <a type="button" class="btn btn-primary">
                                                            <i class="fas fa-search"></i>
                                                          </a>
                                                    </li>
                        </ul>
                    </div>
                </div>



                <div class="col-md-6 right-header">
                    <a asp-action="Logout" asp-controller="Auth">Logout</a>
                </div>


            </div>
        </div>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-3 ourteam">
                    <h3>BOOKSTORE</h3>
                    <p>Our APIs and developer tools (SDKs) can be used to power up a wide range of products</p>
                </div>

                <div class="col-md-3 contact">
                    <h4>About pages</h4>
                    <ul>
                        <li><a href="">Home</a></li>
                        <li><a href="">Categories</a></li>
                        <li><a href="">About us</a></li>
                        <li><a href="">Contact</a></li>
                    </ul>
                </div>

                <div class="col-md-3 contact">
                    <h4>Contract</h4>
                    <ul>
                        <li><a href="">Policy</a></li>
                        <li><a href="">Security</a></li>
                        <li><a href="">Terms</a></li>
                    </ul>
                </div>

                <div class="col-md-3 contact">
                    <h4>Contact</h4>
                    <ul>
                        <li><a href="">Facebook</a></li>
                        <li><a href="">Instagram</a></li>
                        <li><a href="">Gmail</a></li>
                        <li><a href="">Telegram</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
     

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/OwlCarousel2/owl.carousel.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
   
    
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BOOK_STORE_DEMO</title>
    <link rel="stylesheet" href="~/assets/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/assets/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/assets/vendors/typicons/typicons.css">
    <link rel="stylesheet" href="~/assets/vendors/simple-line-icons/css/simple-line-icons.css">
    <link rel="stylesheet" href="~/assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="~/assets/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/assets/js/select.dataTables.min.css">
    <link rel="stylesheet" href="~/assets/css/vertical-layout-light/style.css">
    <link rel="shortcut icon" href="~/assets/images/favicon.png" />
    @RenderSection("Index", required: false)
    @RenderSection("Create", required: false)

</head>
<body>
    <nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex align-items-top flex-row">
        <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-start">
            <div class="me-3">
                <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-bs-toggle="minimize">
                    <span class="icon-menu"></span>
                </button>
            </div>
            <div>
                <a class="navbar-brand brand-logo" href="index.html">
                    BOOKSTORES
                </a>
                <a class="navbar-brand brand-logo-mini" href="index.html">
                    <img src="./assets/images/logo-mini.svg" alt="logo" />
                </a>
            </div>
        </div>
        <div class="navbar-menu-wrapper d-flex align-items-top">
            <ul class="navbar-nav">
                <li class="nav-item font-weight-semibold d-none d-lg-block ms-0">
                    <h1 class="welcome-text">Good Morning, <span class="text-black fw-bold">Thanh Khuat</span></h1>
                    <h3 class="welcome-sub-text">Your performance summary this week </h3>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">

                <li class="nav-item d-none d-lg-block">

                </li>
                <li class="nav-item">
                    <form class="search-form" action="#">
                        <i class="icon-search"></i>
                        <input type="search" class="form-control" placeholder="Search Here" title="Search here">
                    </form>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link count-indicator" id="notificationDropdown" href="#" data-bs-toggle="dropdown">
                        <i class="icon-mail icon-lg"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list pb-0" aria-labelledby="notificationDropdown">
                        <a class="dropdown-item py-3 border-bottom">
                            <p class="mb-0 font-weight-medium float-left">You have 4 new notifications </p>
                            <span class="badge badge-pill badge-primary float-right">View all</span>
                        </a>
                        <a class="dropdown-item preview-item py-3">
                            <div class="preview-thumbnail">
                                <i class="mdi mdi-alert m-auto text-primary"></i>
                            </div>
                            <div class="preview-item-content">
                                <h6 class="preview-subject fw-normal text-dark mb-1">Application Error</h6>
                                <p class="fw-light small-text mb-0"> Just now </p>
                            </div>
                        </a>
                        <a class="dropdown-item preview-item py-3">
                            <div class="preview-thumbnail">
                                <i class="mdi mdi-settings m-auto text-primary"></i>
                            </div>
                            <div class="preview-item-content">
                                <h6 class="preview-subject fw-normal text-dark mb-1">Settings</h6>
                                <p class="fw-light small-text mb-0"> Private message </p>
                            </div>
                        </a>
                        <a class="dropdown-item preview-item py-3">
                            <div class="preview-thumbnail">
                                <i class="mdi mdi-airballoon m-auto text-primary"></i>
                            </div>
                            <div class="preview-item-content">
                                <h6 class="preview-subject fw-normal text-dark mb-1">New user registration</h6>
                                <p class="fw-light small-text mb-0"> 2 days ago </p>
                            </div>
                        </a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link count-indicator" id="countDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="icon-bell"></i>
                        <span class="count"></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list pb-0" aria-labelledby="countDropdown">
                        <a class="dropdown-item py-3">
                            <p class="mb-0 font-weight-medium float-left">You have 7 unread mails </p>
                            <span class="badge badge-pill badge-primary float-right">View all</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item preview-item">
                            <div class="preview-thumbnail">
                                <img src="~/assets/images/faces/face10.jpg" alt="image" class="img-sm profile-pic">
                            </div>
                            <div class="preview-item-content flex-grow py-2">
                                <p class="preview-subject ellipsis font-weight-medium text-dark">Marian Garner </p>
                                <p class="fw-light small-text mb-0"> The meeting is cancelled </p>
                            </div>
                        </a>
                        <a class="dropdown-item preview-item">
                            <div class="preview-thumbnail">
                                <img src="~/assets/images/faces/face12.jpg" alt="image" class="img-sm profile-pic">
                            </div>
                            <div class="preview-item-content flex-grow py-2">
                                <p class="preview-subject ellipsis font-weight-medium text-dark">David Grey </p>
                                <p class="fw-light small-text mb-0"> The meeting is cancelled </p>
                            </div>
                        </a>
                        <a class="dropdown-item preview-item">
                            <div class="preview-thumbnail">
                                <img src="~/assets/images/faces/face1.jpg" alt="image" class="img-sm profile-pic">
                            </div>
                            <div class="preview-item-content flex-grow py-2">
                                <p class="preview-subject ellipsis font-weight-medium text-dark">Travis Jenkins </p>
                                <p class="fw-light small-text mb-0"> The meeting is cancelled </p>
                            </div>
                        </a>
                    </div>
                </li>
                <li class="nav-item dropdown d-none d-lg-block user-dropdown">
                    <a class="nav-link" id="UserDropdown" href="#" data-bs-toggle="dropdown" aria-expanded="false">
                        <img class="img-xs rounded-circle" src="~/assets/images/faces/face8.jpg" alt="Profile image">
                    </a>
                    <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
                        <div class="dropdown-header text-center">
                            <img class="img-md rounded-circle" src="~/assets/images/faces/face8.jpg" alt="Profile image">
                            <p class="mb-1 mt-3 font-weight-semibold">Allen Moreno</p>
                            <p class="fw-light text-muted mb-0">allenmoreno@gmail.com</p>
                        </div>
                        <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-account-outline text-primary me-2"></i> My Profile <span class="badge badge-pill badge-danger">1</span></a>
                        <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-message-text-outline text-primary me-2"></i> Messages</a>
                        <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-calendar-check-outline text-primary me-2"></i> Activity</a>
                        <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-help-circle-outline text-primary me-2"></i> FAQ</a>
                        <a class="dropdown-item"><i class="dropdown-item-icon mdi mdi-power text-primary me-2"></i>Sign Out</a>
                    </div>
                </li>
            </ul>
            <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-bs-toggle="offcanvas">
                <span class="mdi mdi-menu"></span>
            </button>
        </div>
    </nav>
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">

        <!-- partial:partials/_sidebar.html -->
        <nav class="sidebar sidebar-offcanvas" id="sidebar">
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">
                        <i class="mdi mdi-grid-large menu-icon"></i>
                        <span class="menu-title">Home</span>
                    </a>
                </li>
                <li class="nav-item nav-category">Tables Management</li>
                <li class="nav-item">
                    <a asp-area="" asp-controller="Category" asp-action="Index" class="nav-link">
                        <i class="menu-icon ti-layout-menu-v"></i>
                        <span class="menu-title">Category</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a asp-area="" asp-controller="Book" asp-action="ListBook" class="nav-link">
                        <i class="menu-icon ti-package"></i>
                        <span class="menu-title">Book</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"  asp-controller="Admin" asp-action="Order">
                        <i class="menu-icon ti-shopping-cart"></i>
                        <span class="menu-title">Order</span>
                    </a>
                </li>

            </ul>
        </nav>
        <div class="main-panel">
            <div class="content-wrapper">
                @RenderBody()
            </div>

            <footer class="footer">
                <div class="d-sm-flex justify-content-center justify-content-sm-between">
                    <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Premium BOOKSTORE from TEAM 15.</span>
                    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Copyright © 2023. All rights reserved.</span>
                </div>
            </footer>
        </div>
    </div>
   

    <script src="~/assets/vendors/js/vendor.bundle.base.js"></script>
    <script src="~/assets/js/off-canvas.js"></script>
    <script src="~/assets/js/hoverable-collapse.js"></script>
    <script src="~/assets/js/template.js"></script>
    <script src="~/assets/js/settings.js"></script>
    <script src="~/assets/js/todolist.js"></script>
    <script src="~/assets/js/jquery.cookie.js" type="text/javascript"></script>
    <script src="~/assets/js/dashboard.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>