Models/Book.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using BOOK_STORE_DEMO.Dtos;

namespace BOOK_STORE_DEMO.Models
{
    public class Book
    { 
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        public string? Name { get; set; }
        [Required]
        public double Price { get; set; }
        [Required]
        public string? Description { get; set; }
        [Required]
        public string? Author { get; set; }
        public DateTime PublishDate { get; set; }

        public string? Publisher { get; set; }
        public string ?ImageCover { get; set; }
        [ForeignKey("Category")]
        public int CategoryId { get; set; }
        public Category ?Category { get; set; }

      
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;


    }
}

Models/Cart.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace BOOK_STORE_DEMO.Models
{
    public class Cart
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [ForeignKey("User")]
        public int UserId { get; set; }
        public User? User { get; set; }
        
    }
}

Controllers/BookController.cs
using BOOK_STORE_DEMO.Models;
using BOOK_STORE_DEMO.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace BOOK_STORE_DEMO.Controllers
{
    [Authorize(Policy = "ADMIN")]
    public class BookController : Controller
    {
        private readonly IBookService bookService;
        private readonly ICategoryService categoryService;
        private readonly IWebHostEnvironment webHostEnvironment;
        private int pageSize=4;

        public BookController(IBookService bookService, ICategoryService categoryService,IWebHostEnvironment webHostEnvironment)
        {
            this.bookService = bookService;
            this.categoryService = categoryService;
            this.webHostEnvironment = webHostEnvironment;
        }
      
        public IActionResult ListBook()
        {
            IEnumerable<Book> books=bookService.GetAllBooks();
            int pageNum=(int)Math.Ceiling((float)books.Count()/pageSize);
            ViewBag.pageNum=pageNum;
            books=books.Take(pageSize).ToList();
            return View(books);
        }

        [HttpGet]
        public IActionResult Edit(int id) 
        {
            Book book=bookService.GetBookById(id);
            ViewBag.Categories = new SelectList(categoryService.GetAllCategories(), "Id", "Name",book.CategoryId);
            return View(book); 
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Name", "Price", "Description", "Author", "PublishDate", "Publisher,CategoryId")] Book newBook,IFormFile ?imgFile)
        {
            Book oldBook= bookService.GetBookById(id);
            if (oldBook == null)
            {
                return NotFound();
            }
            if(imgFile != null && imgFile.Length > 0 && imgFile.FileName!=oldBook.ImageCover)
            {
                string folderPath = Path.Combine(webHostEnvironment.WebRootPath, "Upload\\images\\");
                string filePath = Path.Combine(folderPath, imgFile.FileName);
                string oldImgFile=Path.Combine(folderPath, oldBook.ImageCover);
                if (System.IO.File.Exists(oldImgFile)==true)
                {
                    System.IO.File.Delete(oldImgFile);
                }
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await imgFile.CopyToAsync(stream);
                }
                oldBook.ImageCover = imgFile.FileName;
            }
            else
            {
                newBook.ImageCover=oldBook.ImageCover;
            }
            oldBook.Name = newBook.Name;
            oldBook.Price= newBook.Price;
            oldBook.CategoryId = newBook.CategoryId;
            oldBook.Description= newBook.Description;
            oldBook.Author=newBook.Author;
            oldBook.PublishDate=newBook.PublishDate;
            oldBook.Publisher=newBook.Publisher;
            bookService.UpdateBook(oldBook);
            return RedirectToAction(nameof(ListBook));
        }

      
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories=new SelectList(categoryService.GetAllCategories(),"Id","Name");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name","Price","Description","Author","PublishDate","Publisher,CategoryId")]Book book,IFormFile imgFile) 
        {
            if(ModelState.IsValid==false)
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors);
                foreach (var error in errors)
                {
                    Console.WriteLine(error.ErrorMessage);
                }
                ViewBag.Categories = new SelectList(categoryService.GetAllCategories(), "Id", "Name");
                return View();
            }
            if (imgFile != null && imgFile.Length>0)
            {
                string folderPath = Path.Combine(webHostEnvironment.WebRootPath, "Upload\\images\\");
                string filePath=Path.Combine(folderPath,imgFile.FileName);
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    await imgFile.CopyToAsync(stream);
                }
                book.ImageCover = imgFile.FileName;
                bookService.AddBook(book);
            }
            return RedirectToAction(nameof(ListBook));
        }

        public IActionResult Delete(int id)
        {
            Book book=bookService.GetBookById(id);
            string folderPath = Path.Combine(webHostEnvironment.WebRootPath, "Upload\\images\\");
            string imgFilePath = Path.Combine(folderPath, book.ImageCover);
            if (System.IO.File.Exists(imgFilePath) == true)
            {
                System.IO.File.Delete(imgFilePath);
            }
            bookService.DeleteBook(id);
            return RedirectToAction(nameof(ListBook));
        }

        public IActionResult Paging(int ?pageIndex)
        {
            int page;
            if (pageIndex == null)
            {
                page = 1;
            }
            else
            {
                page = (int)pageIndex;
            }
            IEnumerable<Book> books = bookService.GetAllBooks();
            IEnumerable<Book> result=books.Skip(pageSize*(page-1)).Take(pageSize);
            return PartialView("BookTable",result);
        }
    }
}

Controllers/CartController.cs
using System.Security.Claims;
using BOOK_STORE_DEMO.Models;
using BOOK_STORE_DEMO.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BOOK_STORE_DEMO.Controllers;
[Authorize]

public class CartController: Controller
{
    private readonly ICartService cartService;
    private readonly ICartItemService cartItemService;
    private readonly IOrderService orderService;
    private readonly IOrderItemService orderItemService;
    private readonly IAuthService authService;
    private readonly ILogger<CartController> _logger;
    
    public CartController(ICartService cartService,
                          ICartItemService cartItemService,
                          IOrderService orderService,
                          IOrderItemService orderItemService,
                          IAuthService authService
                         )
    {
        this.cartService = cartService;
        this.cartItemService = cartItemService;
        this.orderService = orderService;
        this.orderItemService = orderItemService;
        this.authService = authService;
       
    }

    public IActionResult Pay(int id)
    {
        
        List<CartItem> cartItems = cartItemService.GetCartItemsByCartId(id);
        string username = User.FindFirstValue(ClaimTypes.NameIdentifier);
        User user = authService.GetUserByUsername(username);
        Order order = new Order();
        order.CreatedAt=DateTime.Now;
        order.UserId = user.Id;
        Order newOrder = orderService.CreateOrder(order);


        foreach (CartItem cartItem in cartItems)
        {
            
            OrderItem orderItem = CartItemToOrderItem(cartItem,newOrder.Id);
            orderItemService.CreateOrderItem(orderItem);
        }
        
        
       
        
        cartItemService.DeleteCartItemByCartId(id);
      
        TempData["Message"] = "Order created successful!";
        
        return RedirectToAction("Cart", "Home");
    }

    public OrderItem CartItemToOrderItem(CartItem cartItem,int orderId)
    {
        if (cartItem == null || orderId == null)
        {
            return null;
        }
        OrderItem orderItem = new OrderItem();
        orderItem.BookId = cartItem.BookId;
        orderItem.OrderId = orderId;
        orderItem.Quantity = cartItem.Quantity;
        orderItem.Price = (decimal)(cartItem.Book?.Price ?? 0) * cartItem.Quantity;
        return orderItem;

    }
   
}

Controllers/CartItemController.cs
using System.Security.Claims;
using BOOK_STORE_DEMO.Models;
using BOOK_STORE_DEMO.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BOOK_STORE_DEMO.Controllers;
[Authorize]
public class CartItemController:Controller
{
    private readonly ICartService cartService;
    private readonly ICartItemService cartItemService;
    private readonly IAuthService authService;
    

    public CartItemController(ICartService cartService, ICartItemService cartItemService,IAuthService authService)
    {
        this.cartService = cartService;
        this.cartItemService = cartItemService;
        this.authService = authService;
    }
    
    
    public IActionResult CreateCartItem(int bookId)
    {
        string username = User.FindFirstValue(ClaimTypes.NameIdentifier);
        bool bookExistsInCart = false;
        if (String.IsNullOrEmpty(username))
        {
            return RedirectToAction("Login", "Auth");
        }
        Cart cartCurrent = cartService.GetCartByUserUserName(username);
        
        if (cartCurrent == null)
        {
            User user = authService.GetUserByUsername(username);
            Cart cart = new Cart();
            cart.UserId = user.Id;
            cart.User = user;
            cartCurrent = cartService.CreateCart(cart);
        }
        else
        {
            List<CartItem> cartItems = cartItemService.GetCartItemsByCartId(cartCurrent.Id);
            
            foreach (var item in cartItems)
            {
                if (item.BookId == bookId)
                {
                    bookExistsInCart = true;
                    break;

                }

                
            }
        }

        if (bookExistsInCart)
        {
            TempData["ErrorMessage"] = "The book already exists in the shopping cart!";
            return RedirectToAction("Detail", "Home",new { bookId = bookId });
        }
        
        
        

        CartItem cartItem = new CartItem();
        cartItem.BookId = bookId;
        cartItem.CreatedAt=DateTime.Now;
        cartItem.Quantity = 1;
        cartItem.CartId = cartCurrent.Id;
       
        cartItemService.CreateCartItem(cartItem);
        TempData["SuccessMessage"] = "The book has been added to the cart!";
        
        return RedirectToAction("Detail", "Home",new { bookId = bookId });


    }

    public IActionResult UpdateQuantityUp(int id)
    {
        CartItem cartItem = cartItemService.GetCartItemById(id);
        cartItem.Quantity +=1;
        cartItemService.UpdateCartItem(cartItem);
        return RedirectToAction("Cart", "Home");
    }
    public IActionResult UpdateQuantityDown(int id)
    {
        CartItem cartItem = cartItemService.GetCartItemById(id);
        cartItem.Quantity -= 1;
        cartItemService.UpdateCartItem(cartItem);
        return RedirectToAction("Cart", "Home");
    }
    
    public IActionResult DeleteCartItem(int id)
    {
        cartItemService.DeleteCartItemById(id);
        return RedirectToAction("Cart", "Home");
    }
}

Controllers/HomeController.cs
using BOOK_STORE_DEMO.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Security.Claims;
using BOOK_STORE_DEMO.Dtos.Response;
using BOOK_STORE_DEMO.Services;
using Microsoft.AspNetCore.Authorization;
using BOOK_STORE_DEMO.Models;
using BOOK_STORE_DEMO.Dtos;

namespace BOOK_STORE_DEMO.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly IBookService bookService;
        private readonly ICartItemService cartItemService;
        private readonly IAuthService authService;
        private readonly ICartService cartService;
       

        public HomeController(IBookService bookService, ICartItemService cartItemService,IAuthService authService,ICartService cartService)
        {
            this.bookService = bookService;
            this.cartItemService = cartItemService;
            this.authService = authService;
            this.cartService = cartService;
        }

        public IActionResult Index(int? categoryId,int page=1,string search="")
        {
            
            BookResponse bookResponse =bookService.GetBookByFilter(categoryId,page,search);
            return View(bookResponse);
        }

        public IActionResult BooksByFilter(int categoryId, int page=1,string search="")
        {
            BookResponse bookResponse =bookService.GetBookByFilter(categoryId,page,search);
            return PartialView("BookView", bookResponse);
        }

     

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        
        
        public IActionResult Detail(int bookId)
        {
            Book book = bookService.GetBookById(bookId);
            IEnumerable<Book> books = bookService.GetAllBooksByCategory(book.Category.Name);
            BookAndBooksDto bookAndBooks = new BookAndBooksDto()
            {
                Book = book,
                Books = books
            };
            return View(bookAndBooks);
        }
        public IActionResult Cart()
        {
            string username = User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (String.IsNullOrEmpty(username))
            {
                return RedirectToAction("Login", "Auth");
            }

            Cart cart = cartService.GetCartByUserUserName(username);
            if (cart == null)
            {
                Cart newCart = new Cart();
                User user = authService.GetUserByUsername(username);
                newCart.UserId = user.Id;
                cart = cartService.CreateCart(newCart);
            }
           

            IEnumerable<CartItem> cartItems = cartItemService.GetCartItemsByCartId(cart.Id);
           
            decimal totalAmount = 0;
            foreach (var i in cartItems)
            {
                
                decimal price = (decimal)(i.Book?.Price ?? 0);
                totalAmount += price * i.Quantity;
            }
            CartResponse cartResponse = new CartResponse();
            cartResponse.Id = cart.Id;
            cartResponse.CartItems = cartItems;
            cartResponse.Total = totalAmount;
            
           
            return View(cartResponse);
        }
    }
}

VewComponents/RenderCategoryViewComponent.cs
using BOOK_STORE_DEMO.Models;
using BOOK_STORE_DEMO.Services;
using Microsoft.AspNetCore.Mvc;

namespace BOOK_STORE_DEMO.VewComponents;

public class RenderCategoryViewComponent:ViewComponent
{
    private IEnumerable<Category> categories = new List<Category>();
    private readonly ICategoryService categoryService;
   

    public RenderCategoryViewComponent(ICategoryService categoryService)
    {
        this.categoryService = categoryService;
        categories = this.categoryService.GetAllCategories();
    }
    public async Task<IViewComponentResult> InvokeAsync()
    {
        return View("RenderCategory", categories);
    }
   
}

Views/Home/BookView.cshtml
@model BOOK_STORE_DEMO.Dtos.Response.BookResponse
 <div class="row gap-4">    
    
        @if (Model.Books.Count() == 0)
        {
            <div class="col-12" style="text-align: center">
                <p>Not Found Book</p>
            </div>
        }
        else
        {
            
               
            @foreach (var book in Model.Books)
            {
                <a asp-controller="Home" asp-action="Detail" asp-route-bookId="@book.Id" class="col-md-3 block-product">
                    <div class="ImageCover">
                        <img src="~/Upload/images/@book.ImageCover">
                    </div>
                    <h4>@book.Name</h4>
                    <p>by @book.Author</p>
                    <div class="PriceButton">
                        <p>$@book.Price</p>
            
                    </div>
                </a>
            }
               
         
        }
         </div>
    
<div style="margin: 30px auto;text-align: center">
         <nav aria-label="Page navigation example">
             <ul class="pagination" style="display: flex;justify-content: center;margin: 30px">
                 @foreach (var i in Enumerable.Range(1, Model.TotalPages))
                 {
                     <li class="page-item @(Model.CurrentPage == i ? "active" : "") li-page" id="@i">
                         <a class="page-link">@i</a>
                     </li>
                 }
    
             </ul>
         </nav>
     
     </div>

Views/Home/Cart.cshtml
@{
    ViewData["Title"] = "DetailProduct";
    Layout = "MyLayout";
    
}
@model BOOK_STORE_DEMO.Dtos.Response.CartResponse
<div class="container mt-5 mb-5">
    <div class="d-flex justify-content-center row">
        <div class="col-md-8">
            <div class="p-2">
                <h4>Shopping cart</h4>
                       
            </div>
            @foreach (var i in Model.CartItems)
            {
                <div class="d-flex flex-row justify-content-between align-items-center p-2 bg-white mt-4 px-3 rounded">
                    <div class="mr-1"><img class="rounded" src="~/Upload/images/@i.Book?.ImageCover" width="70"></div>
                    <div class="d-flex flex-column align-items-center product-details"><span class="font-weight-bold">@i.Book?.Name</span>
                               
                    </div>
                    <div class="d-flex flex-row align-items-center qty">
                        @if (@i.Quantity == 1)
                        {
                            <a asp-action="DeleteCartItem" asp-controller="CartItem" asp-route-id="@i.Id">
                                <i class="fa fa-minus text-danger"></i>
                            </a>
                        }
                        else
                        {
                            <a asp-action="UpdateQuantityDown" asp-controller="CartItem" asp-route-id="@i.Id">
                                <i class="fa fa-minus text-danger"></i>
                            </a>
                        }
                              
                        <h5 class="text-grey mt-1 mr-1 ml-1">@i.Quantity</h5>
                        <a asp-action="UpdateQuantityUp" asp-controller="CartItem" asp-route-id="@i.Id">
                            <i class="fa fa-plus text-success"></i>
                        </a>

                    </div>
                           
                    <div>
                        <h5 class="text-grey">$@((decimal)(i.Book?.Price??0) *i.Quantity)</h5>
                                
                    </div>
                    <div class="d-flex align-items-center">
                        <a asp-action="DeleteCartItem" asp-controller="CartItem" asp-route-id="@i.Id">
                            <i class="fa fa-trash mb-1 text-danger"></i>
                        </a> 
                                
                    </div>
                </div>
                       
            }
                   
            <div class="d-flex flex-row align-items-center mt-3 p-2 bg-white rounded">Total: $@Model.Total</div>
            <div class="d-flex flex-row align-items-center mt-3 p-2 bg-white rounded"><a asp-controller="Cart" asp-action="Pay" asp-route-id="@Model.Id" class="btn btn-warning btn-block btn-lg ml-2 pay-button" type="button">Proceed to Pay</a></div>
        </div>
    </div>
</div>
@section Scripts{
    <script>
          var message = '@TempData["Message"]' || '';
       		
               if (message) {
                  alert(message)
                  @TempData.Remove("Message");
               }
    </script>
    
}

Views/Home/Detail.cshtml
@{
    ViewData["Title"] = "DetailProduct";
    Layout = "MyLayout";
}
@model BOOK_STORE_DEMO.Dtos.BookAndBooksDto
<div class="container">

	<div class="card-custom">
		<div class="container-fliud">
			<div class="wrapper row">
				<div class="preview col-md-6">
						
					<div class="preview-pic tab-content">
						<div class="tab-pane active" id="pic-1"><img class="img-custom" src="~/Upload/images/@Model.Book.ImageCover" /></div>
						
					</div>
						
						
				</div>
				<div class="details col-md-6">
                    <h3 class="product-title">@Model.Book.Name</h3>
                    <p class="price">price: <span>$@Model.Book.Price</span></p>
                    <p class="product-description">Description: @Model.Book.Description</p>
                    <p class="product-description">Author: <span>@Model.Book.Author</span></p>
                    <p class="product-description">Category: <span>@Model.Book.Category?.Name</span></p>
                    <p class="product-description">Publisher: <span>@Model.Book.Publisher</span></p>
                    <p class="product-description">Publish Date: <span>@Model.Book.PublishDate</span></p>
						
						
					<div class="action">
                        <a asp-action="CreateCartItem" asp-route-bookId="@Model.Book.Id" asp-controller="CartItem" class="add-to-cart btn btn-default" type="button">add to cart</a>
					</div>
				</div>
			</div>
            <div class="row my-5">
                <h1 class="text-center">Featured Products</h1>
            </div>

            <div class="row g-4 my-5 mx-auto owl-carousel owl-theme">
                @foreach(var item in Model.Books)
                {
                    <div class="col product-item mx-auto">
                        <div class="product-img">
                            <img src="~/Upload/images/@item.ImageCover" alt="" class="img-fluid d-block mx-auto">
                            <div class="row g-1 btns w-100 mx-auto text-center">
                                <button type="button" class="col-6 py-2">
                                    <a asp-action="CreateCartItem" asp-route-bookId="@item.Id" asp-controller="CartItem" type="button" class="related-product-link"><i class="fa fa-cart-plus"></i>Add to Cart</a>
                                </button>
                                <button type="button" class="col-6 py-2">
                                    <a class="a-cleanup related-product-link" asp-controller="Home" asp-action="Detail" asp-route-bookId="@item.Id"><i class="fa fa-binoculars"></i> View</a>
                                </button>
                            </div>
                        </div>

                        <div class="product-info p-3">
                            <span class="product-type">@item.Category?.Name</span>
                            <a href="#" class="d-block text-dark text-decoration-none py-2 product-name">@item.Name</a>
                            <span class="product-price">$@item.Price</span>
                        </div>
                    </div>
                }
            </div>
		</div>
	</div>

</div>


@section Scripts{
	<script>
        var errorMessage = '@TempData["ErrorMessage"]' || '';
		var successMessage = '@TempData["SuccessMessage"]' || '';
        if (errorMessage) {
           alert(errorMessage)
           @TempData.Remove("ErrorMessage");
        }
		if (successMessage){
			alert(successMessage)
            @TempData.Remove("SuccessMessage");
		}
    </script>

    <script>
        $('.owl-carousel').owlCarousel({
            loop: true,
            margin: 6,
            responsiveClass: true,
            responsive: {
                0: {
                    items: 1,
                },
                768: {
                    items: 2,
                },
                1100: {
                    items: 3,
                },
                1400: {
                    items: 4,
                    loop: false,
                }
            }
        });
    </script>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "MyLayout";
}
@model BOOK_STORE_DEMO.Dtos.Response.BookResponse

<div>
    <div class="filter-container">

        @await Component.InvokeAsync("RenderCategory")
    </div>
    <div id="content">
         <div class="row gap-4">    
            
                @if (Model.Books.Count() == 0)
                {
                    <div class="col-12">
                        <p>Not Found Book</p>
                    </div>
                }
                else
                {
                    
                       
                            @foreach (var book in Model.Books)
                            {
                                <a asp-controller="Home" asp-action="Detail" asp-route-bookId="@book.Id" class="col-md-3 block-product">
                                    <div class="ImageCover">
                                        <img src="~/Upload/images/@book.ImageCover">
                                    </div>
                                    <h4>@book.Name</h4>
                                    <p>by @book.Author</p>
                                    <div class="PriceButton">
                                        <p>$@book.Price</p>
            
                                    </div>
                                </a>
                            }
                       
                 
                }
                 </div>
            
           <div>
                 <nav aria-label="Page navigation example">
                     <ul class="pagination" style="display: flex;justify-content: center;margin: 30px">
                         @foreach (var i in Enumerable.Range(1, Model.TotalPages))
                         {
                             <li class="page-item @(Model.CurrentPage == i ? "active" : "") li-page" id="@i">
                                 <a class="page-link">@i</a>
                             </li>
                         }
            
                     </ul>
                 </nav>
             
             </div>

    </div>
    
  

    
</div>

@section Scripts {
    <script>

       var categoryId = 0;
       var page = 1;
       var searchStr="";
   
       // Tạo một hàm để xử lý việc load dữ liệu
       function loadData(categoryId, page) {
           let data={ categoryId, page };
           if (searchStr!=""){
               data={...data,search:searchStr}
           }
           $.ajax({
               url: "BooksByFilter",
               data,
               success: function (response) {
                   $("div#content").html(response);
                   // Gọi lại mã JavaScript cho PartialView ở đây
                   initializePartialView();
               }
           });
       }
       
       
      
   
       // Đăng ký sự kiện click cho các nút category
       $(".li-category-id").click(function (e) {
           categoryId = $(this).attr("id");
           page = 1; // Reset page về 1 khi thay đổi category
           searchStr="";
         
   
           loadData(categoryId, page);
       });
   
       // Đăng ký sự kiện click cho các nút page
       $(".li-page").click(function (e) {
           page = $(this).attr("id");
           
   
           loadData(categoryId, page);
       });
   
       // Hàm khởi tạo mã JavaScript cho PartialView
       function initializePartialView() {
           // Đặt lại sự kiện click cho các nút page trong PartialView ở đây
           $(".li-page").click(function (e) {
               page = $(this).attr("id");
   
               loadData(categoryId, page);
           });
       }
       //Search
       $(".btn-search").click(function (e){   
           page = 1;
           searchStr=$("#search-input").val();
         
           loadData( categoryId,page);
          
       })
       
   </script>



}